---

- name: Install nginx and associated packages
  apt: name=nginx state=latest


- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx