---
 
- name: Create the Drupal database
  postgresql_db: 
   name:  Drupal 
   state: present
   encoding: 'UTF-8'
  become_user: postgres
 

- name: Create the Drupal user
  postgresql_user: 
    db:  Drupal 
    name: Drupal 
    password:  password 
    priv: ALL
  become_user: postgres

- name: Set byteaoutput to escape with another method
  shell: psql -U postgres -c 'ALTER DATABASE "Drupal" SET bytea_output = 'escape';' 
   
  


    